### ISSUE TITLE
Does Storyblok SDK support Next.js 14? 

### ISSUE THREAD

**Issue by goofygoobers** [storyblok/storyblok-react#876] opened 2023-12-21 02:27 UTC
### Description

Hello Storyblok maintainers and community,

I have a question regarding the compatibility of the Storyblok SDK with Next.js version 14.

I've been following the "Render Storyblok Stories Dynamically in Next.js 14" tutorial, which can be found [here](https://www.storyblok.com/tp/render-storyblok-stories-dynamically-in-next-js-14). 

However, while following the tutorial, I noticed a prerequisite mentioned in the Requirements section. It directs me to another tutorial titled "Add a Headless CMS to Next.js in 5 Minutes," accessible [here](https://www.storyblok.com/tp/add-a-headless-cms-to-next-js-in-5-minutes). The confusing part is that the prerequisites for this tutorial include:

- [next@12.1.0](mailto:next@12.1.0)
- [react@17.0.2](mailto:react@17.0.2)
- @storyblok/[react@1.0.3](mailto:react@1.0.3)

It's a little confusing that the prerequisite tutorial appears to be for Next.js 12, yet it's linked to the parent tutorial for Next.js 14. 

Could you kindly provide clarification regarding the compatibility of the Storyblok SDK with Next.js 14 and its App directory? If compatibility exists, I would greatly appreciate it if you could share any relevant documentation and specify the SDK version numbers.

Thank you for your assistance!

### Suggested solution or improvement

Is there an updated version of Add a Headless CMS to Next.js in 5 minutes tutorial for NextJS 14? 

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by fgiuliani** [comment] 2023-12-21 22:11
Hi @goofygoobers thanks for catching the issue!

Indeed, we do have an updated version of the 5-minute tutorial for Next.js 13 (and therefore 14). You can find it here:
https://www.storyblok.com/tp/add-a-headless-cms-to-next-js-13-in-5-minutes

You can read more about the different approaches to using Storyblok SDK with the App Router here:
https://github.com/storyblok/storyblok-react/?tab=readme-ov-file#nextjs-using-app-router---live-editing-support

Looks like we linked the wrong tutorial there. We will fix it 😄
cc @arorachakit

**Comment by goofygoobers** [comment] 2023-12-22 01:38
@fgiuliani thanks for getting back to me. 

Just to confirm that version below is the correct one? 

```"@storyblok/react": "^2.1.0",```

Because I am getting the follwowing import error for this line ```import { storyblokInit, apiPlugin } from '@storyblok/react/rsc';```

```Cannot find module '@storyblok/react/rsc' or its corresponding type declarations.ts(2307)```

**Comment by fgiuliani** [comment] 2023-12-22 02:26
@goofygoobers we just released a version 3.0.0. That one should work

**Comment by goofygoobers** [comment] 2023-12-22 03:42
I've just tried upgrading to ```"@storyblok/react": "^3.0.0",```

But still getting the error ```Cannot find module '@storyblok/react/rsc' or its corresponding type declarations.ts(2307)```

**Comment by fgiuliani** [comment] 2023-12-22 03:45
@goofygoobers can you check that the value for `moduleResolution` in your `tsconfig.json` file is `nodenext`?

You can read more about that here:
https://github.com/storyblok/storyblok-react/issues/613#issuecomment-1683077548

**Comment by eduardfossas** [comment] 2023-12-22 10:26
Hello, @fgiuliani. I was just setting up a basic next.js 14 with the links that you sent, but for some reason, the live editor does not work as expected. It looks like it is refreshing each time without showing my live editing previews:


https://github.com/storyblok/storyblok-react/assets/5878978/11b1cfc9-4f20-470f-b7b0-a53889c97fa2

**Comment by fgiuliani** [comment] 2023-12-22 11:27
Hi @eduardfossas,
Can you check the two different approaches we propose for Next.js 13 (and 14) with our React SDK and verify if there is something different on your project?

Here you have an example with real-time support:
https://github.com/storyblok/storyblok-react/tree/main/playground-next13-live-editing

And here you have a Full Server Components example (only refreshing when clicking on the Save button):
https://github.com/storyblok/storyblok-react/tree/main/playground-next13-rsc

**Comment by eduardfossas** [comment] 2023-12-22 11:40
Hello, @fgiuliani 

Thank you for your reply.
In this past hour, I cloned the https://github.com/storyblok/next.js-13-boilerplate repo and I created a new space in storyblok and set up the preview token and it only works when I click the save button.

**Comment by serGlazkov** [comment] 2023-12-22 13:16
same problem as @eduardfossas

**Comment by serGlazkov** [comment] 2023-12-22 13:50
looks like problem here
just remove `story` from useEffect deps
<img width="758" alt="Screenshot 2023-12-22 at 20 48 56" src="https://github.com/storyblok/storyblok-react/assets/5631994/d834560b-ae8d-41e2-a20b-804a4ce17598">

**Comment by serGlazkov** [comment] 2023-12-27 12:28
@yannic-wtfoxtrot could you take a look? ^

**Comment by yannic-wtfoxtrot** [comment] 2024-01-02 08:36
I touched this part of the code recently when removing conditional use effect calls. From what I can tell this should work when moving the id (line 18) out of the useEffect callback and adding it to the dependency array. Feel free to provide a PR :)

**Comment by arorachakit** [comment] 2024-01-03 14:36
Thank you for working on it everyone. 
I will also take a look at it, and I will add @fgiuliani to the PR reviewer as well so he can take a look :) 

@goofygoobers - Regarding the link to the wrong tutorial, it looks like it got published accidentally without being completed. I am taking it down for now.

**Comment by nx-alejandrolacasa** [comment] 2024-01-08 16:43
After updating to `"@storyblok/react": "3.0.1"`, the `useStoryblokState` stopped working for me using the pages folder. The hook returns the same story over and over, even though I am sending a new one when navigating.

I've rolled back just the `useStoryblokState` hook, and everything works fine with that, I've redone all changes one by one, and the issue is the removal of this condition:
```jsx
  if (!isBridgeEnable || !initialStory) {
    return initialStory;
  }
```

Restoring that, everything works as expected. In my case, `isBridgeEnable` is `false`, and therefore the initialStory (the latest one) is returned, which is expected to make the navigation work.

I am using the same code as the pages folder example in the REAME page, nothing fancy.

**Comment by arorachakit** [comment] 2024-01-08 16:50
Hey @nx-alejandrolacasa ! 
Thanks for reporting. 
We are taking a look at it :) 

cc - @fgiuliani @alexjoverm

**Comment by serGlazkov** [comment] 2024-01-08 17:52
Check the PR https://github.com/storyblok/storyblok-react/pull/885
This should fix the problem with updating the initialStory

**Comment by fgiuliani** [comment] 2024-01-08 18:20
Hey @nx-alejandrolacasa we just merged the PR created by @serGlazkov . Looks like we missed a setState on the changes. Can you try now?

**Comment by nx-alejandrolacasa** [comment] 2024-01-09 13:02
Hi @fgiuliani and @arorachakit,

The fix works and now the proper story is returned by the hook.

Thanks for the quick fix! 🚀

**Comment by arorachakit** [comment] 2024-01-11 11:53
Awesome! 
Thanks everyone, I will close this issue now. Feel free to create a new one in case there is any other issue :)

**Closed by arorachakit** 2024-01-11 11:53 UTC
Labels: enhancement, pending-author, pending-triage
