### ISSUE TITLE
LICENSE file is missing

### ISSUE THREAD

**Issue by stschroeder** [storyblok/storyblok-react#193] opened 2022-08-18 10:58 UTC
Hi there 👋.

I noticed that the source code currently does not contain a LICENSE file. Under which license is the code currently released? And could you please also add this information in the form of a LICENSE file to this repository?

See also [Adding a license to a repository](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) and [package-json#license](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#license).

Thanks in advance!

**Comment by colinhowe** [comment] 2023-11-23 18:40
Giving this a bump. We're adopting Storyblok and the lack of a license here is creating a minor SOC2 headache for us.

**Comment by Barokai** [comment] 2023-11-24 06:58
bumping this too, as i am curious about that. 
https://choosealicense.com/ by github could help to find the appropriate license

**Comment by nx-dennytrebbin** [comment] 2023-11-24 12:16
To ensure compliance, our tools discovered no license for this project.
Unfortunately, end users interact with Storyblok and as such, the unlicensed code in question causes some trouble for us.

**Comment by nx-dennytrebbin** [comment] 2023-11-28 07:19
The project's license was intended to be MIT, but the PR got closed (without comments) instead of merged.

https://github.com/storyblok/storyblok-react/pull/58

**Comment by dariusrosendahl** [comment] 2024-01-09 10:21
@fgiuliani @phlipper Could somebody elaborate what the plan is? Would be nice to tell some larger clients that there's no license problem. :)

**Comment by richardtaylordawson** [comment] 2024-06-27 21:18
Bumping this :)

**Comment by marckraw** [comment] 2024-07-02 11:28
👍🏻

**Comment by dlhck** [comment] 2024-10-04 16:56
@edodusi could you please take a look at this? I hope/assume this will be MIT licensed. For enterprise clients this is very important.

**Comment by edodusi** [comment] 2024-10-04 17:41
@dlhck I will check ASAP, thanks for bringing this to my attention

**Closed** 2024-10-11 09:09 UTC
Labels: documentation

**Comment by dlhck** [comment] 2024-10-11 09:29
thanks @edodusi ! 👏🏼
