### ISSUE TITLE
Missing types for StoryblokStory

### ISSUE THREAD

**Issue by terhuerne** [storyblok/storyblok-react#613] opened 2023-07-06 11:54 UTC
### Describe the issue you're facing

When trying to import the StoryblokStory component into a NextJS 13 application, I receive an error that the type declaration is missing. However, the component loads in the frontend so I guess it is just an issue with the types.
<img width="922" alt="Bildschirmfoto 2023-07-06 um 13 50 24" src="https://github.com/storyblok/storyblok-react/assets/7851686/b5e34cec-f8c7-44f0-8077-515e2ab6981b">

### Reproduction

...

### Steps to reproduce

Follow the https://www.storyblok.com/tp/add-a-headless-cms-to-next-js-13-in-5-minutes and create a Next 13 application with typescript support. Follow along the steps and then, the linting in VSCode will show the error. 

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 1014.52 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.1.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.6.4 - /opt/homebrew/bin/npm
    Watchman: 2023.05.15.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by fgiuliani** [comment] 2023-07-07 11:33
Hi @terhuerne,

Can you check if the issue is related to the one reported here?
https://github.com/storyblok/storyblok-react/issues/570

**Comment by terhuerne** [comment] 2023-07-17 17:29
Yes, I have implemented the fix on my project already, but the bindings are still missing. I will investigate further tomorrow.

**Comment by CedYF** [comment] 2023-08-09 18:38
same problem

**Comment by terhuerne** [comment] 2023-08-10 11:25
I haven't figured out yet, why this happens with the lib. As a workaround, I've created my own StoryblokStory component and the error is gone. But this can only be a temporary fix. So for everyone, who wants to get rid of the error message please create your own StoryblokStory component and use this code:

`"use client";

import { ISbStoryData, StoryblokBridgeConfigV2, StoryblokComponent } from "@storyblok/react/rsc";
import { useStoryblokState } from '@storyblok/react';
import { forwardRef } from "react";

interface StoryblokStoryProps {
    story: ISbStoryData | null;
    bridgeOptions: StoryblokBridgeConfigV2;
    [key: string]: unknown;
}
  
const StoryblokStory = forwardRef<HTMLElement, StoryblokStoryProps>(
    ({ story, bridgeOptions, ...restProps }, ref) => {
        if (typeof story?.content === "string") {
            story.content = JSON.parse(story.content);
        }
        story = useStoryblokState(story, bridgeOptions);
        return <StoryblokComponent ref={ref} blok={story?.content} {...restProps} />;
    }
);

export default StoryblokStory;
`

**Comment by johannesstrueber** [comment] 2023-08-10 11:38
i am having the same issues. It is working although it is not exported from rsc.mjs ?

**Comment by fgiuliani** [comment] 2023-08-14 21:13
Hey @CedYF @terhuerne @johannesstrueber can you update to the latest version of the SDK and check if the error is still happening?
If it is, can you share some steps to reproduce the error?

Just for you to know, two weeks ago we introduced a new change/feature on the SDK that allows developers to import StoryblokStory from the same `rsc` package:

```
import { StoryblokStory } from "@storyblok/react/rsc";

export default async function Home() {
  const { data } = await fetchData();

  return (
    <div>
      <StoryblokStory story={data.story} />
    </div>
  );
}
```

https://github.com/storyblok/storyblok-react#3-fetch-content-and-render-components

You can read more here:
https://github.com/storyblok/storyblok-react/pull/654

**Comment by johannesstrueber** [comment] 2023-08-15 07:33
Hey @fgiuliani  i did a quick codesandbox setup using the code of the [next13 rsc playground](https://github.com/storyblok/storyblok-react/tree/main/playground-next13-rsc) with the latest version 2.4.4. 

https://codesandbox.io/p/sandbox/adoring-joana-y3dg27

**Comment by johannesstrueber** [comment] 2023-08-15 07:43
Hey @fgiuliani  i did a quick setup in codesandbox using the example from the [next 13 rsc ](https://github.com/storyblok/storyblok-react/tree/main/playground-next13-rsc) playground and added the latest version of the package.

https://codesandbox.io/p/sandbox/adoring-joana-y3dg27

<img width="562" alt="Bildschirmfoto 2023-08-15 um 09 42 42" src="https://github.com/storyblok/storyblok-react/assets/45170421/2829d65a-962d-47ab-bee4-bed153413317">

**Comment by fgiuliani** [comment] 2023-08-15 23:20
Hi @johannesstrueber thank you!

Can I ask you a favor? As I'm getting some mixed results when trying to replicate the issue locally:
What happens if instead of using the latest version of the SDK, you use the version `v2.2.1`, and you change the import for `StoryblokStory`?

`import StoryblokStory from "@storyblok/react/story"`

**Comment by fgiuliani** [comment] 2023-08-17 22:50
Hi @johannesstrueber,

after reviewing for some time different ideas and points, I saw that the project you shared in codesandbox has the `moduleResolution` config set to `node` in `tsconfig.json`.

We had some issues in the past related to that:
https://github.com/storyblok/storyblok-react/issues/570#issuecomment-1591207805

I changed the `moduleResolution` to `nodenext` in codesandbox and looks like working. Can you confirm?

Having said that, which default value are you getting for `moduleResolution` when you create a brand new Next.js project using `create-next-app`?

**Comment by johannesstrueber** [comment] 2023-08-18 21:30
Hey @fgiuliani thanks for your time. 

The `nodenext` option  for `moduleResolution` in the `tsconfig.json` fixed it.

I just copied the `tsconfig.json` file from your playground example which has the `node` config option in it. Maybe that should be adjusted?

When i run `create next-app` with typescript support i get `bundler` as config option for the `moduleResolution` which also gets the types.

**Comment by fgiuliani** [comment] 2023-08-19 13:31
Thanks for your input, feedback, and taking the time to test it @johannesstrueber!
You are totally right, we should adjust that on the playgrounds of the React SDK. I will do that and link the commit to this issue, in order to close it.

@CedYF @terhuerne can you confirm that fixes it for you, too?

**Comment by fgiuliani** [comment] 2023-08-19 13:46
Changes applied:

https://github.com/storyblok/storyblok-react/commit/a280e59f5e1aa6aed34ae5be2469da4222514eff

**Closed** 2023-08-23 11:34 UTC
Labels: bug
