### ISSUE TITLE
Bridge is not working in Production build

### ISSUE THREAD

**Issue by sendy34** [storyblok/storyblok-react#113] opened 2022-06-28 23:41 UTC
On dev server, bridge is working fine, 
however, on production version (client facing), we wanted the client to edit things but bridge is not working there.

Even a local production build in next js doesn't render Bridge inside editor.

Any solution?

**Comment by sendy34** [comment] 2022-06-28 23:49
Setting up bridge = true also doesn't work
```
storyblokInit({
    bridge: true,
    accessToken: '<access-token>',
    use: [apiPlugin],
    components,
})
```

**Comment by fgiuliani** [comment] 2022-06-29 15:52
Hi @sendy34 @annarhughes thank you for reaching out.

Which `accessToken` are you using in the production environment, whenever you want to enable the real time editing experience? The `preview` token or the `public` one?

I'll check with the Storyblok team and keep you updated

**Comment by sendy34** [comment] 2022-06-29 18:09
@fgiuliani We are using `preview` token

**Comment by fgiuliani** [comment] 2022-06-29 22:47
Thank you @sendy34. I'll be discussing with the team about this issue

**Comment by annarhughes** [comment] 2022-07-05 11:22
Hey @fgiuliani 

We've updated to 1.0.11 and that fix is working for that specific issue of using `preview` param (ty!), but it hasn't solved this production issue.

We're using [Incremental Static Regeneration](https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration), with next.js preview mode set up, as in the docs above. And now with the preview fix in 1.0.11 we're using `useStoryblokState` like so:

```
interface Props {
  story: StoryData;
  preview: boolean;
  storyblokParams: StoryParams;
  locale: string;
}

export default function Page(props: Props) {
  const { story, preview } = props;
  const editableStory: StoryData = useStoryblokState(story, {}, preview);

  return <StoryblokComponent blok={editableStory.content} />;
}
```

Before the fix in 1.0.11 we were using `useStoryblokState(story);`, which was defaulting to the same as above, so we're seeing the same on 1.0.11 as we were on 1.0.10

The preview is definitely half working, as heres the difference between when preview is on for production vs local:

**When preview is on for production:**
- next.js preview cookies are applied correctly ✅
- updating data -> save -> refresh the page -> new draft data shows ✅
- storyblok tags e.g. `data-blok-c` are applied to components ✅
- components are highlighted in the visual editor on hover (dotted outlines) ✅
- components are clickable on in the visual editor, updating the right panel to the selected component ❌
- data updates in real time when editing in the right panel ❌

**When preview is on for local:**
- next.js preview cookies are applied correctly ✅
- updating data -> save -> refresh the page -> new draft data shows ✅
- storyblok tags e.g. `data-blok-c` are applied to components ✅
- components are highlighted in the visual editor on hover (dotted outlines) ✅
- components are clickable on in the visual editor, updating the right panel to the selected component ✅
- data updates in real time when editing in the right panel  ✅

When preview if off completely, all of the above are not working, as expected.

**Comment by fgiuliani** [comment] 2022-07-06 23:09
Thanks for the details provided @annarhughes. We'll be taking a look and will keep you updated

**Comment by sendy34** [comment] 2022-07-06 23:29
> 

yes, we are using `useStoryblokState` as well.
We are not using `SSG` since we had to use `getInitialProps` on `_app` for some reason which disabled `SSG`

```
const Home: React.FC<IProps> = ({ story }) => {
    story = useStoryblokState(story)

    return (
        <>
            <Head>
                <title>{story ? story.name : 'Calibrate'}</title>
            </Head>
            <StoryblokComponent blok={story.content}  />
        </>
    )
}```

**Comment by imabp** [comment] 2022-07-09 05:06
@sendy34 Storyblok Bridge is not meant to use in production.
Read this [here](https://www.storyblok.com/docs/guide/essentials/visual-editor#installing-the-storyblok-js-bridge) to know more.

Few strong reason to support this.

1. You do not edit things in production. Hence Bridge is good for, staging and development environment only.
2. Real time visual editing  is not performant for deeply nested react components. The issue is still being worked on. Tagging @lisilinhart  for more about that part. Meanwhile, you can refer this [forum question too](https://forum.storyblok.com/t/next-js-problems-with-visual-bridge-in-real-time/461/5)

---
cc: @fgiuliani @annarhughes

**Comment by johannes-lindgren** [comment] 2022-07-09 09:36
Hi @imabp, I'm afraid I have to disagree with that assessment. Content editors need to preview their content on the production deployment because that is the version of the site that the end-users will see. The point of the preview is to see what the content will look like once it is published. If the content is being previewed on another build, then the published site may be different from the previewed site. They are not developers, so they are not interested in running into all the bugs that typically flourish on staging builds.

Besides, staging deployments would suffer from the same issues in this ticket anyways. They are also production builds, i.e. they are not running in dev mode.

What you should do is to load the bridge dynamically if and only if the site is embedded within the Visual Editor. You can detect this by listening for postMessage events from the parent window. In this way, regular end-users of the site won't be impacted, and content editors can get an accurate preview of their content. This mechanism is handled by this library thought, so nothing you (should) have to think about.

To address your points:
1. All changes from the Storyblok bridge are confined to the client, i.e. the browser. Nothing is being changed on the production build, nor in Storyblok's database.
2. Real time visual editing is by no means more performant on development builds.

**Comment by imabp** [comment] 2022-07-09 11:15
> What you should do is to load the bridge dynamically if and only if the site is embedded within the Visual Editor. You can detect this by listening for postMessage events from the parent window. In this way, regular end-users of the site won't be impacted, and content editors can get an accurate preview of their content. This mechanism is handled by this library thought, so nothing you (should) have to think about.

This is nice approach. Thanks for that.
Yes I agree on the part, content writers need to preview things out in production, so should not use the dev mode.

**Comment by fgiuliani** [comment] 2022-07-11 18:10
hey @sendy34 have you taken a look at the `bridge` parameter of the `storyblokInit` function?

https://github.com/storyblok/storyblok-react#initialization

You can read more about it here, on the `@storyblok/js` package README file. `@storyblok/react` includes the code of `@storyblok/js`:
https://github.com/storyblok/storyblok-js#storyblok-bridge

**Comment by imabp** [comment] 2022-07-11 18:12
@sendy34 try using the following

```ts

const isDev = process.env.NODE_ENV === 'development'

if(isDev)
{
    // handler for storyblok bridge.
}

```

**Comment by annarhughes** [comment] 2022-07-19 10:20
@fgiuliani are you able to give a rough estimate on when this will be looked into? Our team has held off starting content, waiting to get the full editor experience, so some idea would be really helpful 🙏

**Comment by fgiuliani** [comment] 2022-07-19 12:58
hey @annarhughes we're planning to work on some edits related to the React SDK between this and the following week.

In the meantime, have you seen the messages from @johannes-lindgren and @imabp

**Comment by imabp** [comment] 2022-07-19 15:01
@fgiuliani I guess the issue is solved. We can close this.

**Comment by annarhughes** [comment] 2022-07-19 15:16
@fgiuliani thanks, still believe there's bugs on the sdk related to live editing on production/staging sites, but it would be good to even just have this confirmed to not be a bug. i.e. if the team can't reproduce the issues we're seeing, we know it's something in our setup

**Comment by annarhughes** [comment] 2022-07-19 16:52
@fgiuliani just saw #112 , hopefully fixing some of those fixes the production build issue.
But this issue does seem specific to _only_ production as it works in localhost. The half preview state (specifically that 
components are highlighted in the visual editor on hover (dotted outlines) ✅) suggests the bridge is loaded but not fully completed/hit some bugs.

Our setup is

In `config/storyblok.ts`

```
import { apiPlugin, storyblokInit } from '@storyblok/react';


const storyblok = storyblokInit({
  accessToken: process.env.NEXT_PUBLIC_STORYBLOK_TOKEN,
  // apiOptions: {  },
  use: [apiPlugin],
  components: {
    page: StoryblokPage,
    // ...
  },
});

export default storyblok;
```

In `_app.ts`

```
// Init storyblok
storyblok;

function MyApp({ Component, pageProps, includeLayout = true }: Props) {
```

So it's initialised by importing the init function, outside of the App function. Is it worth loading otherwise like inside a useEffect?

**Comment by sendy34** [comment] 2022-07-20 21:18
@imabp 
Sorry, even setting `bridge` to `true` doesn't work in production build.

I updated the package to latest 1.0.14 version and set the init like this

```
storyblokInit({
    bridge: true,
    accessToken: '<ACCESS_TOKEN_WAS_ADDED_HERE>',
    apiOptions: {
        cache: { type: 'memory' },
    },
    use: [apiPlugin],
    components,
})```

but it bridge only works in localhost (dev env) and not in production build

**Comment by sendy34** [comment] 2022-07-29 02:24
Finally found a workaround.
Thanks to this code: https://github.com/storyblok/storyblok-react/issues/156#issuecomment-1197980100

----

1. Disabling the bridge by setting bridge false
2. Implementing custom bridge

Don't forget to load `drafts` by checking if you are in `preview` mode (if you are using NextJS Preview feature).
Because custom bridge only works on draft posts.

---

### getStoryblokBridge.js
```
let bridgePromise

const loadBridge = () => {
    return new Promise((resolve, reject) => {
        if (typeof window === 'undefined') {
            return
        }
        if (document.getElementById('storyblok-javascript-bridge')) {
            return
        }

        const script = document.createElement('script')
        script.async = true
        script.src = 'https://app.storyblok.com/f/storyblok-v2-latest.js'
        script.id = 'storyblok-javascript-bridge'

        script.onerror = (error) => {
            reject(error)
            console.log(error)
        }
        script.onload = () => {
            resolve(new window.StoryblokBridge())
        }

        document.getElementsByTagName('head')[0].appendChild(script)
    })
}

export const getStoryblokBridge = async () => {
    if (!bridgePromise) {
        bridgePromise = loadBridge()
    }

    return bridgePromise
}

export const USE_STORYBLOK_BRIDGE = typeof window !== 'undefined'
```

----

### useEditableContent.js
```
import { useEffect, useState } from 'react'
import { getStoryblokBridge, USE_STORYBLOK_BRIDGE } from './getStoryblokBridge'

export const useEditableContent = (initialPage) => {
    const [page, setPage] = useState(initialPage)

    useEffect(() => {
        setPage(initialPage)
    }, [initialPage])

    useEffect(() => {
        let bridge
        ;(async () => {
            if (USE_STORYBLOK_BRIDGE) {
                bridge = await getStoryblokBridge()

                bridge.on('input', (event) => {
                    if (event) {
                        setPage(event.story)
                    }
                })
                bridge.on(['change', 'published'], () =>
                    window.location.reload()
                )
            }
        })()

        return () => {}
    }, [])

    return page
}
```


----
### _app.tsx
```
storyblokInit({
    bridge: false,
    accessToken: '<TOKEN-HERE>',
    apiOptions: {
        cache: { type: 'memory' },
    },
    use: [apiPlugin],
    components,
})
```

----
### [[...slug]].tsx
```
const Home: React.FC<IProps> = ({ story: s, blogs }) => {
const story = useEditableContent(s)
....
....
export const getStaticProps: GetStaticProps = async ({ params, preview }) => {
    // load the story based on preview
    // if preview is true, then load draft
}
```

**Closed** 2022-07-29 02:25 UTC

**Comment by annarhughes** [comment] 2022-08-08 12:29
@fgiuliani this has been closed however it still seems there is an issue? this workaround isnt actually documented by the team and i'd rather not use a workaround and have the bridge fixed in the package. 

Could you please provide an update on when we can expect fixes for these bugs?

**Comment by fgiuliani** [comment] 2022-08-08 23:20
Hi @annarhughes the creator of the issue closed it. Could you create a new one to keep track of the specific problem you are facing? If you can share again the steps you are following and the problems you are getting, that would be super helpful.

Sorry for the back and forth, we've been pretty busy with the launch of the new Storyblok V2. We'll be having some chats and meetings with the DevRel team about SDKs during the next couple of weeks.

On the other hand, as the SDKs are open source, feel free to introduce any change in case you find a solution for your specific issue.
