### ISSUE TITLE
Browser freezes in preview mode

### ISSUE THREAD

**Issue by minortom** [storyblok/storyblok-react#62] opened 2022-05-05 14:55 UTC
When using Next.js (with SSR) in combination with the Storyblok Bridge (https://app.storyblok.com/f/storyblok-v2-latest.js). Preview mode will freeze after editing multiple components. This is because the `data-blok-focused="true"` will be triggered two times first, and incrementally after editing/changing fields in the editor. 

`window.addEventListener("click", this.handleWindowClick.bind(this)),`

This gets triggered everytime I edit a field in the editor (v1).

`storyblokInit` is initialised only one time in _app.tsx

What can I do?

**Comment by kevin-edmister** [comment] 2022-05-11 22:46
I can confirm this issue. Also using Next JS in preview mode locally.

**Comment by minortom** [comment] 2022-05-27 06:33
Any news, comments or even acknowledgement from your side? For now we use [https://github.com/storyofams/storyblok-toolkit](https://github.com/storyofams/storyblok-toolkit). But we specially refactored our application to use your "official" library to leverage new features and keep up to date (read: invested time for our client). Let me know if you need anything else?

**Comment by fgiuliani** [comment] 2022-05-28 20:53
Hi @minortom and @kevin-edmister! Thanks for reporting this issue and sorry for the delay in the response. The DevRel team was very busy during these days.

Could you share with us a list of steps to reproduce the issue? Is this only happening when you use the "Preview Mode" of Next.js?

Is it happening to you only with the new React SDK?
https://www.npmjs.com/package/@storyblok/react

Was it happening with the previous one?
https://www.npmjs.com/package/storyblok-react

**Comment by minortom** [comment] 2022-05-30 14:21
Hi @fgiuliani, thank you for your answer. No problem, I understand.

Steps needed to reproduce this issue in "Preview Mode" (Next.js): 

- Download an install `https://github.com/storyblok/storyblok-react/tree/feature/v1/playground-next` with all of its dependencies
- Configure your preview token
- Do some changes to use the demo environment (I've used a demo Storyblok instance)
- Keep editing two or more components.. Your browser will eventually freeze because of all the DOM updates mentioned above.

I haven't tried using the "old" storyblok-react. Is that one based on `app.storyblok.com/f/storyblok-latest.js`? If that is the case, we currently use `https://github.com/storyofams/storyblok-toolkit/blob/master/src/bridge/init.ts#L6` which is based on this with no problems.

**Comment by fgiuliani** [comment] 2022-06-01 15:36
hey @minortom we're taking a look at the issue with the team.
I was not able to reproduce it, I'm not sure I'm following the correct steps.

Would you be able to record your screen showing when the issue is happening?
You mentioned "Preview Mode". Is it happening ONLY when you are using the Next.js Preview Mode?

Thank you

cc @christianzoppi

**Comment by fweth** [comment] 2022-06-28 06:57
Happened to me as well (Next.js), on Chrome / Ubuntu, my colleague working on Chrome / MacOS didn't have the problem.  Maybe we are not talking about the same thing, but in my case it seems like a redirect into the void, not a freeze, I can continue to use the Browser but the Storyblok site is broken.  I downloaded the GNOME Web browser, which is based on WebKit, and didn't have any issues with it.

**Comment by jestanoff** [comment] 2022-07-04 22:16
@fgiuliani @christianzoppi
I have reproduced it and recorded a video. My setup was pretty simple as per https://www.storyblok.com/docs/guide/getting-started#next, I just forked https://stackblitz.com/edit/getting-started-next and setup a new space on storyblok. 

You can clearly see on the video how some random clicking/editing leads to a memory leak that eats 800Mb of RAM in like 20s, moreover it seems to get in some kind of preview loop that happens even when I don't touch anything. It keeps leaking memory until chrome decides to kill that service worker along with the iFrames, usually after using 2-3 GB. On my main project it kills both the preview iframe in storyblok and a localhost:3000 tab.

For references I'm using an apple M1 laptop with 16GB of memory.

Download [video](https://drive.google.com/file/d/1pCht4Erxlt3OkFjxyfK-D6aghy9VjdDy/view) and play it in a browser

**Comment by fgiuliani** [comment] 2022-07-06 23:07
Thank you for the details and the video @jestanoff. We'll be taking a look with the team and keep you updated. We're trying to identify where the issue is happening and what would be a way of fixing it.

**Comment by fgiuliani** [comment] 2022-08-01 17:53
Hey @jestanoff I created a PR with a change I think should help with this issue. 

https://github.com/storyblok/storyblok-react/pull/164

I'm adding all the logic when the Storyblok Bridge is registered inside a `useEffect` call. When this PR gets merged, you can update the version of the SDK in your project and check if this issue keeps happening

**Closed** 2022-08-03 11:37 UTC
